name: Go

on:
  push:
    branches:
    - fltk
    - dev
  pull_request:
    branches:
    - fltk
    - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      working-directory: ${{github.workspace}}/cmdline
      run: go build -v ./...

    - name: Test
      working-directory: ${{github.workspace}}/lib
      run: go test -v ./...
